/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import java.util.Date;
import java.io.File;
import android.graphics.Bitmap;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class CallAudioTrackBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean isRecording;
	private Date timestamp;
	private String phoneNumber;
	private String contactName;
	private File dataFile;
	private Bitmap portrait;
	private int callType;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the isRecording
	 */
	public boolean getIsRecording() {
		return isRecording;
	}

	/**
	 * @param isRecording the isRecording to set
	 */
	public void setIsRecording(boolean isRecording) {
		boolean old = this.isRecording;
		this.isRecording = isRecording;
		this.emitter.firePropertyChange("isRecording", old, this.isRecording);
	}

	/**
	 * @return the timestamp
	 */
	public Date getTimestamp() {
		return timestamp;
	}

	/**
	 * @param timestamp the timestamp to set
	 */
	public void setTimestamp(Date timestamp) {
		Date old = this.timestamp;
		this.timestamp = timestamp;
		this.emitter.firePropertyChange("timestamp", old, this.timestamp);
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		String old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the contactName
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * @param contactName the contactName to set
	 */
	public void setContactName(String contactName) {
		String old = this.contactName;
		this.contactName = contactName;
		this.emitter.firePropertyChange("contactName", old, this.contactName);
	}

	/**
	 * @return the dataFile
	 */
	public File getDataFile() {
		return dataFile;
	}

	/**
	 * @param dataFile the dataFile to set
	 */
	public void setDataFile(File dataFile) {
		File old = this.dataFile;
		this.dataFile = dataFile;
		this.emitter.firePropertyChange("dataFile", old, this.dataFile);
	}

	/**
	 * @return the portrait
	 */
	public Bitmap getPortrait() {
		return portrait;
	}

	/**
	 * @param portrait the portrait to set
	 */
	public void setPortrait(Bitmap portrait) {
		Bitmap old = this.portrait;
		this.portrait = portrait;
		this.emitter.firePropertyChange("portrait", old, this.portrait);
	}

	/**
	 * @return the callType
	 */
	public int getCallType() {
		return callType;
	}

	/**
	 * @param callType the callType to set
	 */
	public void setCallType(int callType) {
		int old = this.callType;
		this.callType = callType;
		this.emitter.firePropertyChange("callType", old, this.callType);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "CallAudioTrackBean ["+
                "isRecording=" + this.isRecording +
                " , timestamp=" + this.timestamp +
                " , phoneNumber=" + this.phoneNumber +
                " , contactName=" + this.contactName +
                " , dataFile=" + this.dataFile +
                " , portrait=" + this.portrait +
                " , callType=" + this.callType +
        "]";
    }	

}
