/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import java.util.List;
import com.wxxr.mobile.callhelper.app.model.Channel;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class DXHZSettingBean extends SettingBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean noDisturbingInNight;
	private boolean chatMode;
	private boolean isSaveInPhoneBox;
	private boolean everyHZ;
	private List<Channel> channels;
	private boolean hzreportRemind;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the noDisturbingInNight
	 */
	public boolean getNoDisturbingInNight() {
		return noDisturbingInNight;
	}

	/**
	 * @param noDisturbingInNight the noDisturbingInNight to set
	 */
	public void setNoDisturbingInNight(boolean noDisturbingInNight) {
		boolean old = this.noDisturbingInNight;
		this.noDisturbingInNight = noDisturbingInNight;
		this.emitter.firePropertyChange("noDisturbingInNight", old, this.noDisturbingInNight);
	}

	/**
	 * @return the chatMode
	 */
	public boolean getChatMode() {
		return chatMode;
	}

	/**
	 * @param chatMode the chatMode to set
	 */
	public void setChatMode(boolean chatMode) {
		boolean old = this.chatMode;
		this.chatMode = chatMode;
		this.emitter.firePropertyChange("chatMode", old, this.chatMode);
	}

	/**
	 * @return the isSaveInPhoneBox
	 */
	public boolean getIsSaveInPhoneBox() {
		return isSaveInPhoneBox;
	}

	/**
	 * @param isSaveInPhoneBox the isSaveInPhoneBox to set
	 */
	public void setIsSaveInPhoneBox(boolean isSaveInPhoneBox) {
		boolean old = this.isSaveInPhoneBox;
		this.isSaveInPhoneBox = isSaveInPhoneBox;
		this.emitter.firePropertyChange("isSaveInPhoneBox", old, this.isSaveInPhoneBox);
	}

	/**
	 * @return the everyHZ
	 */
	public boolean getEveryHZ() {
		return everyHZ;
	}

	/**
	 * @param everyHZ the everyHZ to set
	 */
	public void setEveryHZ(boolean everyHZ) {
		boolean old = this.everyHZ;
		this.everyHZ = everyHZ;
		this.emitter.firePropertyChange("everyHZ", old, this.everyHZ);
	}

	/**
	 * @return the channels
	 */
	public List<Channel> getChannels() {
		return channels;
	}

	/**
	 * @param channels the channels to set
	 */
	public void setChannels(List<Channel> channels) {
		List<Channel> old = this.channels;
		this.channels = channels;
		if(this.channels != null){
            this.channels = new ListDecorator<Channel>("channels", this.emitter,this.channels);
        }
		this.emitter.firePropertyChange("channels", old, this.channels);
	}

	/**
	 * @return the hzreportRemind
	 */
	public boolean getHzreportRemind() {
		return hzreportRemind;
	}

	/**
	 * @param hzreportRemind the hzreportRemind to set
	 */
	public void setHzreportRemind(boolean hzreportRemind) {
		boolean old = this.hzreportRemind;
		this.hzreportRemind = hzreportRemind;
		this.emitter.firePropertyChange("hzreportRemind", old, this.hzreportRemind);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "DXHZSettingBean ["+
                "noDisturbingInNight=" + this.noDisturbingInNight +
                " , chatMode=" + this.chatMode +
                " , isSaveInPhoneBox=" + this.isSaveInPhoneBox +
                " , everyHZ=" + this.everyHZ +
                " , channels=" + this.channels +
                " , hzreportRemind=" + this.hzreportRemind +
        "]";
    }	

}
