/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import com.wxxr.mobile.callhelper.app.model.HtmlContent;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class HtmlMessageBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String remoteURL;
	private long readTime;
	private Long msgId;
	private long serialVersionUID;
	private HtmlContent htmlMessage;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the remoteURL
	 */
	public String getRemoteURL() {
		return remoteURL;
	}

	/**
	 * @param remoteURL the remoteURL to set
	 */
	public void setRemoteURL(String remoteURL) {
		String old = this.remoteURL;
		this.remoteURL = remoteURL;
		this.emitter.firePropertyChange("remoteURL", old, this.remoteURL);
	}

	/**
	 * @return the readTime
	 */
	public long getReadTime() {
		return readTime;
	}

	/**
	 * @param readTime the readTime to set
	 */
	public void setReadTime(long readTime) {
		long old = this.readTime;
		this.readTime = readTime;
		this.emitter.firePropertyChange("readTime", old, this.readTime);
	}

	/**
	 * @return the msgId
	 */
	public Long getMsgId() {
		return msgId;
	}

	/**
	 * @param msgId the msgId to set
	 */
	public void setMsgId(Long msgId) {
		Long old = this.msgId;
		this.msgId = msgId;
		this.emitter.firePropertyChange("msgId", old, this.msgId);
	}

	/**
	 * @return the serialVersionUID
	 */
	public long getSerialVersionUID() {
		return serialVersionUID;
	}

	/**
	 * @param serialVersionUID the serialVersionUID to set
	 */
	public void setSerialVersionUID(long serialVersionUID) {
		long old = this.serialVersionUID;
		this.serialVersionUID = serialVersionUID;
		this.emitter.firePropertyChange("serialVersionUID", old, this.serialVersionUID);
	}

	/**
	 * @return the htmlMessage
	 */
	public HtmlContent getHtmlMessage() {
		return htmlMessage;
	}

	/**
	 * @param htmlMessage the htmlMessage to set
	 */
	public void setHtmlMessage(HtmlContent htmlMessage) {
		HtmlContent old = this.htmlMessage;
		this.htmlMessage = htmlMessage;
		this.emitter.firePropertyChange("htmlMessage", old, this.htmlMessage);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "HtmlMessageBean ["+
                "remoteURL=" + this.remoteURL +
                " , readTime=" + this.readTime +
                " , msgId=" + this.msgId +
                " , serialVersionUID=" + this.serialVersionUID +
                " , htmlMessage=" + this.htmlMessage +
        "]";
    }	

}
