/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MissCallsSettingBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean isOpenMissCall;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the isOpenMissCall
	 */
	public boolean getIsOpenMissCall() {
		return isOpenMissCall;
	}

	/**
	 * @param isOpenMissCall the isOpenMissCall to set
	 */
	public void setIsOpenMissCall(boolean isOpenMissCall) {
		boolean old = this.isOpenMissCall;
		this.isOpenMissCall = isOpenMissCall;
		this.emitter.firePropertyChange("isOpenMissCall", old, this.isOpenMissCall);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "MissCallsSettingBean ["+
                "isOpenMissCall=" + this.isOpenMissCall +
        "]";
    }	

}
