/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class MissCallsSettingBean extends SettingBean implements IBindableBean {

}
