/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import java.util.List;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class PrivateSMSettingBean extends SettingBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String bindingMail;
	private List<String> phoneNumber;
	private boolean isPasswordSetup;
	private String password;
	private boolean isOpenPrivateSms;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the bindingMail
	 */
	public String getBindingMail() {
		return bindingMail;
	}

	/**
	 * @param bindingMail the bindingMail to set
	 */
	public void setBindingMail(String bindingMail) {
		String old = this.bindingMail;
		this.bindingMail = bindingMail;
		this.emitter.firePropertyChange("bindingMail", old, this.bindingMail);
	}

	/**
	 * @return the phoneNumber
	 */
	public List<String> getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(List<String> phoneNumber) {
		List<String> old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		if(this.phoneNumber != null){
            this.phoneNumber = new ListDecorator<String>("phoneNumber", this.emitter,this.phoneNumber);
        }
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the isPasswordSetup
	 */
	public boolean getIsPasswordSetup() {
		return isPasswordSetup;
	}

	/**
	 * @param isPasswordSetup the isPasswordSetup to set
	 */
	public void setIsPasswordSetup(boolean isPasswordSetup) {
		boolean old = this.isPasswordSetup;
		this.isPasswordSetup = isPasswordSetup;
		this.emitter.firePropertyChange("isPasswordSetup", old, this.isPasswordSetup);
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		String old = this.password;
		this.password = password;
		this.emitter.firePropertyChange("password", old, this.password);
	}

	/**
	 * @return the isOpenPrivateSms
	 */
	public boolean getIsOpenPrivateSms() {
		return isOpenPrivateSms;
	}

	/**
	 * @param isOpenPrivateSms the isOpenPrivateSms to set
	 */
	public void setIsOpenPrivateSms(boolean isOpenPrivateSms) {
		boolean old = this.isOpenPrivateSms;
		this.isOpenPrivateSms = isOpenPrivateSms;
		this.emitter.firePropertyChange("isOpenPrivateSms", old, this.isOpenPrivateSms);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "PrivateSMSettingBean ["+
                "bindingMail=" + this.bindingMail +
                " , phoneNumber=" + this.phoneNumber +
                " , isPasswordSetup=" + this.isPasswordSetup +
                " , password=" + this.password +
                " , isOpenPrivateSms=" + this.isOpenPrivateSms +
        "]";
    }	

}
