/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class RegionBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private String pRegionName;
	private String phoneNumber;
	private String regionName;
	private long pRegionId;
	private String brandName;
	private long regionId;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the pRegionName
	 */
	public String getPRegionName() {
		return pRegionName;
	}

	/**
	 * @param pRegionName the pRegionName to set
	 */
	public void setPRegionName(String pRegionName) {
		String old = this.pRegionName;
		this.pRegionName = pRegionName;
		this.emitter.firePropertyChange("pRegionName", old, this.pRegionName);
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		String old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the regionName
	 */
	public String getRegionName() {
		return regionName;
	}

	/**
	 * @param regionName the regionName to set
	 */
	public void setRegionName(String regionName) {
		String old = this.regionName;
		this.regionName = regionName;
		this.emitter.firePropertyChange("regionName", old, this.regionName);
	}

	/**
	 * @return the pRegionId
	 */
	public long getPRegionId() {
		return pRegionId;
	}

	/**
	 * @param pRegionId the pRegionId to set
	 */
	public void setPRegionId(long pRegionId) {
		long old = this.pRegionId;
		this.pRegionId = pRegionId;
		this.emitter.firePropertyChange("pRegionId", old, this.pRegionId);
	}

	/**
	 * @return the brandName
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * @param brandName the brandName to set
	 */
	public void setBrandName(String brandName) {
		String old = this.brandName;
		this.brandName = brandName;
		this.emitter.firePropertyChange("brandName", old, this.brandName);
	}

	/**
	 * @return the regionId
	 */
	public long getRegionId() {
		return regionId;
	}

	/**
	 * @param regionId the regionId to set
	 */
	public void setRegionId(long regionId) {
		long old = this.regionId;
		this.regionId = regionId;
		this.emitter.firePropertyChange("regionId", old, this.regionId);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "RegionBean ["+
                "pRegionName=" + this.pRegionName +
                " , phoneNumber=" + this.phoneNumber +
                " , regionName=" + this.regionName +
                " , pRegionId=" + this.pRegionId +
                " , brandName=" + this.brandName +
                " , regionId=" + this.regionId +
        "]";
    }	

}
