/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import android.graphics.Bitmap;
import java.util.List;
import com.wxxr.mobile.callhelper.app.model.SMSInfo;
import com.wxxr.mobile.core.ui.common.ListDecorator;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class SMSSessionGroupBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private boolean isHasUnRead;
	private String phoneNumber;
	private String showSessionContent;
	private String contactName;
	private List<SMSInfoBean> sms;
	private String portrait;
	private int size;
	private String date;
	
	
	
	private boolean selected;
	
	
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		boolean old = this.selected;
		this.selected = selected;
		this.emitter.firePropertyChange("selected", old, this.selected);
		
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		String old = this.date;
		this.date = date;
		this.emitter.firePropertyChange("date", old, this.date);
	}

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the isHasUnRead
	 */
	public boolean getIsHasUnRead() {
		return isHasUnRead;
	}

	/**
	 * @param isHasUnRead the isHasUnRead to set
	 */
	public void setIsHasUnRead(boolean isHasUnRead) {
		boolean old = this.isHasUnRead;
		this.isHasUnRead = isHasUnRead;
		this.emitter.firePropertyChange("isHasUnRead", old, this.isHasUnRead);
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		String old = this.phoneNumber;
		this.phoneNumber = phoneNumber;
		this.emitter.firePropertyChange("phoneNumber", old, this.phoneNumber);
	}

	/**
	 * @return the showSessionContent
	 */
	public String getShowSessionContent() {
		return showSessionContent;
	}

	/**
	 * @param showSessionContent the showSessionContent to set
	 */
	public void setShowSessionContent(String showSessionContent) {
		String old = this.showSessionContent;
		this.showSessionContent = showSessionContent;
		this.emitter.firePropertyChange("showSessionContent", old, this.showSessionContent);
	}

	/**
	 * @return the contactName
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * @param contactName the contactName to set
	 */
	public void setContactName(String contactName) {
		String old = this.contactName;
		this.contactName = contactName;
		this.emitter.firePropertyChange("contactName", old, this.contactName);
	}

	/**
	 * @return the sms
	 */
	public List<SMSInfoBean> getSms() {
		return sms;
	}

	/**
	 * @param sms the sms to set
	 */
	public void setSms(List<SMSInfoBean> sms) {
		List<SMSInfoBean> old = this.sms;
		this.sms = sms;
		if(this.sms != null){
            this.sms = new ListDecorator<SMSInfoBean>("sms", this.emitter,this.sms);
        }
		this.emitter.firePropertyChange("sms", old, this.sms);
	}

	/**
	 * @return the portrait
	 */
	public String getPortrait() {
		return portrait;
	}

	/**
	 * @param portrait the portrait to set
	 */
	public void setPortrait(String portrait) {
		String old = this.portrait;
		this.portrait = portrait;
		this.emitter.firePropertyChange("portrait", old, this.portrait);
	}

	/**
	 * @return the size
	 */
	public int getSize() {
		return size;
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(int size) {
		int old = this.size;
		this.size = size;
		this.emitter.firePropertyChange("size", old, this.size);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "SMSSessionGroupBean ["+
                "isHasUnRead=" + this.isHasUnRead +
                " , phoneNumber=" + this.phoneNumber +
                " , showSessionContent=" + this.showSessionContent +
                " , contactName=" + this.contactName +
                " , sms=" + this.sms +
//                " , portrait=" + this.portrait +
                " , size=" + this.size +
        "]";
    }	

}
