/*
 * Generated code, don't modified !
 */
package com.wxxr.mobile.callhelper.app.bean;

import android.graphics.Bitmap;
import com.wxxr.mobile.core.bean.api.IBindableBean;
import com.wxxr.mobile.core.bean.api.IPropertyChangeListener;
import com.wxxr.mobile.core.ui.common.BindableBeanSupport;

/**
 * Generated by Bindable Bean generator
 *
 */
public class UserDetailBean implements IBindableBean {
	
	private final BindableBeanSupport emitter = new BindableBeanSupport(this);
	private int birthday;
	private Bitmap icon;
	private String moblie;
	private Boolean updated;
	private String nickName;
	private boolean male;
	private String province;
	private String userName;

	/**
	 * @param listener
	 */
	public void addPropertyChangeListener(IPropertyChangeListener listener) {
		emitter.addPropertyChangeListener(listener);
	}

	/**
	 * @param listener
	 */
	public void removePropertyChangeListener(IPropertyChangeListener listener) {
		emitter.removePropertyChangeListener(listener);
	}
	
	@Override
	public boolean hasPropertyChangeListener(IPropertyChangeListener listener) {
		return emitter.hasPropertyChangeListener(listener);
	}



	/**
	 * @return the birthday
	 */
	public int getBirthday() {
		return birthday;
	}

	/**
	 * @param birthday the birthday to set
	 */
	public void setBirthday(int birthday) {
		int old = this.birthday;
		this.birthday = birthday;
		this.emitter.firePropertyChange("birthday", old, this.birthday);
	}

	/**
	 * @return the icon
	 */
	public Bitmap getIcon() {
		return icon;
	}

	/**
	 * @param icon the icon to set
	 */
	public void setIcon(Bitmap icon) {
		Bitmap old = this.icon;
		this.icon = icon;
		this.emitter.firePropertyChange("icon", old, this.icon);
	}

	/**
	 * @return the moblie
	 */
	public String getMoblie() {
		return moblie;
	}

	/**
	 * @param moblie the moblie to set
	 */
	public void setMoblie(String moblie) {
		String old = this.moblie;
		this.moblie = moblie;
		this.emitter.firePropertyChange("moblie", old, this.moblie);
	}

	/**
	 * @return the updated
	 */
	public Boolean getUpdated() {
		return updated;
	}

	/**
	 * @param updated the updated to set
	 */
	public void setUpdated(Boolean updated) {
		Boolean old = this.updated;
		this.updated = updated;
		this.emitter.firePropertyChange("updated", old, this.updated);
	}

	/**
	 * @return the nickName
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * @param nickName the nickName to set
	 */
	public void setNickName(String nickName) {
		String old = this.nickName;
		this.nickName = nickName;
		this.emitter.firePropertyChange("nickName", old, this.nickName);
	}

	/**
	 * @return the male
	 */
	public boolean getMale() {
		return male;
	}

	/**
	 * @param male the male to set
	 */
	public void setMale(boolean male) {
		boolean old = this.male;
		this.male = male;
		this.emitter.firePropertyChange("male", old, this.male);
	}

	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		String old = this.province;
		this.province = province;
		this.emitter.firePropertyChange("province", old, this.province);
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		String old = this.userName;
		this.userName = userName;
		this.emitter.firePropertyChange("userName", old, this.userName);
	}

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override   
    public String toString() {
        return "UserDetailBean ["+
                "birthday=" + this.birthday +
                " , icon=" + this.icon +
                " , moblie=" + this.moblie +
                " , updated=" + this.updated +
                " , nickName=" + this.nickName +
                " , male=" + this.male +
                " , province=" + this.province +
                " , userName=" + this.userName +
        "]";
    }	

}
